sudo: required
services:
  - docker

before_install:
  - docker build -t renatodvm/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true renatodvm/react-test npm test

after_success:
  - docker build -t renatodvm/multi-client ./client
  - docker build -t renatodvm/multi-nginx ./nginx
  - docker build -t renatodvm/multi-server ./server
  - docker build -t renatodvm/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push renatodvm/multi-client
  - docker push renatodvm/multi-nginx
  - docker push renatodvm/multi-server
  - docker push renatodvm/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-901681299924
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY

